config/routes.rb
Rails.application.routes.draw do
  root to: 'memo#index'
  resources :memo, only: [:new,:create,:edit,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content,{presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memo_controller.rb
class MemoController < ApplicationController
  before_action :set_post,only:[:edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else
      redirect_to new_memo_path
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      redirect_to edit_memo_path(@post.id)
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memo_helper.rb
module MemoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/memo/edit.html.erb
<h1>Edit</h1>
<%= @post.content %>
<%= form_tag("/memo/#{@post.id}", method: :patch) do %>
<input type="text" name="content" maxlength='50'>
<input type="submit" value="Edit">
<% end %>
<%= link_to 'Top','/' %>

app/views/memo/index.html.erb
<div class="form-inline">
<h1 class="mr-auto">MemoApp</h1>
<%= form_tag('/memo',method: :post) do %>
  
  <input type="text" name="content" maxlength='50' class="form-control">
  <input type="submit" value="New Post" class="btn btn-light">
  
<% end %>
</div>
<div class="messages row">
<% @posts.each do |post| %>
   <div class="col-sm-3">
    <ul class="content">
     <li class="message">
     <strong>
      <%= post.content %>
     </strong>
      <ul>
       <li class="btn">
        <%= link_to 'edit',edit_memo_path(post), class: "btn btn-success" %> <%= link_to 'delete',memo_path(post.id),class: "btn btn-dark",method: :delete %>
       </li>
    </ul>
   </li>
  </ul>
  </div>
<% end %> 
</div>